apiVersion: v2
name: kadalu
icon: https://kadalu.io/static/css/logo.png
description: Contains chart for deploying Kadalu Operator
type: application
# Development placeholder replaced in every chart during release packaging.
version: 0.0.0-dev.0
dependencies:
  - name: common
    repository: file://charts/common
    version: 0.0.0-dev.0
  - name: operator
    repository: file://charts/operator
    version: 0.0.0-dev.0
    condition: operator.enabled
