#!/bin/bash

set -euo pipefail

KADALU_NAMESPACE=${KADALU_NAMESPACE:-kadalu}
KADALU_SELECTOR='app.kubernetes.io/part-of=kadalu'

kubectl delete daemonset,statefulset,deployment,service \
  -l "${KADALU_SELECTOR}" -n "${KADALU_NAMESPACE}" --ignore-not-found
kubectl delete serviceaccount \
  kadalu-csi-provisioner kadalu-csi-nodeplugin kadalu-operator kadalu-server-sa \
  -n "${KADALU_NAMESPACE}" --ignore-not-found
kubectl delete role \
  kadalu-operator kadalu-csi-leader-election kadalu-csi-provisioner \
  -n "${KADALU_NAMESPACE}" --ignore-not-found
kubectl delete rolebinding \
  kadalu-operator kadalu-csi-leader-election kadalu-csi-provisioner \
  -n "${KADALU_NAMESPACE}" --ignore-not-found
kubectl delete configmap kadalu-info \
  -n "${KADALU_NAMESPACE}" --ignore-not-found

kubectl get storageclass -o name \
  | awk '/^storageclass.storage.k8s.io\/kadalu\./' \
  | xargs -r kubectl delete

kubectl delete csidriver kadalu --ignore-not-found
kubectl delete customresourcedefinition \
  kadalustorages.kadalu-operator.storage --ignore-not-found
kubectl delete clusterrole \
  kadalu-operator \
  kadalu-csi-external-attacher \
  kadalu-csi-external-provisioner \
  kadalu-csi-external-resizer \
  kadalu-csi-nodeplugin \
  kadalu-csi-provisioner \
  pod-exec \
  --ignore-not-found
kubectl delete clusterrolebinding \
  kadalu-operator \
  kadalu-csi-external-attacher \
  kadalu-csi-external-provisioner \
  kadalu-csi-external-resizer \
  kadalu-csi-nodeplugin \
  kadalu-csi-provisioner \
  --ignore-not-found

if kubectl api-resources --api-group=security.openshift.io -o name \
  | awk '$0 == "securitycontextconstraints.security.openshift.io" { found=1 } END { exit !found }'; then
  kubectl delete securitycontextconstraints.security.openshift.io \
    kadalu-scc --ignore-not-found
fi

if [[ "${KADALU_DELETE_NAMESPACE:-false}" == "true" ]]; then
  kubectl delete namespace "${KADALU_NAMESPACE}" --ignore-not-found
else
  echo "Preserved namespace ${KADALU_NAMESPACE}." \
    "Set KADALU_DELETE_NAMESPACE=true to delete it."
fi
