#!/bin/bash
set -euo pipefail

KADALU_NAMESPACE=${KADALU_NAMESPACE:-kadalu}
kubectl get pods -n "${KADALU_NAMESPACE}" -o name \
  | awk '/-csi-/' \
  | xargs -r kubectl delete -n "${KADALU_NAMESPACE}"
