#!/bin/bash

TAG="${TAG:-local}"
DOCKER_USER="${DOCKER_USER:-joejulian}"
IMAGES_HUB="${IMAGES_HUB:-ghcr.io}"

export DOCKER_USER IMAGES_HUB
export KADALU_VERSION="${TAG}"

# Build everything required from latest changes

make build-containers
make gen-manifest

# This makes the docker start to check image here first
docker tag "${DOCKER_USER}/kadalu-server:${TAG}" "${IMAGES_HUB}/${DOCKER_USER}/kadalu-server:${TAG}"
docker tag "${DOCKER_USER}/kadalu-operator:${TAG}" "${IMAGES_HUB}/${DOCKER_USER}/kadalu-operator:${TAG}"
docker tag "${DOCKER_USER}/kadalu-csi:${TAG}" "${IMAGES_HUB}/${DOCKER_USER}/kadalu-csi:${TAG}"

# Change this to pick the local image
sed -i -e 's/Always/IfNotPresent/g' manifests/kadalu-operator.yaml
sed -i -e 's/Always/IfNotPresent/g' manifests/kadalu-operator-openshift.yaml


# Now run the operator too
set +e
which oc > /dev/null
if [ $? -eq 0 ]; then
    oc create -f manifests/kadalu-operator-openshift.yaml
else
    kubectl apply -f manifests/kadalu-operator.yaml
fi


echo "To reset everything, and start from fresh state, run clean"
echo ""
echo "  sudo ./extras/scripts/cleanup"
echo ""
echo "----"
